
RV_GNU := riscv64-linux-gnu
SHELL  := /bin/bash

C_SRCS := $(wildcard *.c)
S_SRCS := $(wildcard *.s)
LD_SRC := $(TARGET).ld

#GCC_OPTS += -mabi=ilp32 -march=rv32i -static -mcmodel=medany -nostdlib -nostartfiles -T $(LD_SRC)
GCC_OPTS := -march=rv32i -mabi=ilp32 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -T $(LD_SRC) -Wl,--build-id=none
SRCS = $(C_SRCS) $(S_SRCS)

all: $(TARGET).elf

$(TARGET).elf: $(SRCS)
	$(RV_GNU)-gcc $(GCC_OPTS) $^ -o $@
#	$(RV_GNU)-objdump -D -Mnumeric $@ > $(basename $@).dump
	$(RV_GNU)-objdump -D -Mnumeric --disassembler-options=no-aliases $@ > $(basename $@).dump
#	$(RV_GNU)-strip -R .comment -R .note.gnu.build-id $@
#	$(RV_GNU)-objdump -D -Mnumeric $@ > $(basename $@).sdump
	$(RV_GNU)-objcopy $(basename $@).elf -O binary $(basename $@).bin
	$(RV_GNU)-bin2hex -w 32 $(basename $@).bin $(basename $@).hex
#	sed -i '1i @0' $(basename $@).hex

clean:
	rm -f *.elf *.dump *.sdump *.hex *.bin

.PHONY: target
